resources:
  - name: dbp_repo2
    type: GitRepo
    configuration:
      gitProvider: my_github                       # <-- replace with your integration
      path: KatsuyaHoshii/cicd-jfrog-cli-github-actions    # <-- replace with your repository name
      branches:
        include: master

  - name: dbp_image2
    type: Image
    configuration:
      registry: art                                # <-- replace with your artifactory integration
      sourceRepository: dockerlocal               # <-- required if registry is Artifactory
      imageName: trialhisol202107.jfrog.io/docker-local/cicd-jfrog-cli-github-actions  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info2
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: dbp_build2
      buildNumber: 1    

  - name: dbp_promoted_build_info2
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: dbp_build2
      buildNumber: 1
      

pipelines:
  - name: pipeline_dbp2
    steps:
      - name: npm_test
        type: Bash
        configuration:
          affinityGroup: dbp_group
        execution:
          onStart:
            - ls -la
            - cd cicd-jfrog-cli-github-actions
            - ls -la
            - npm install
            - npm test
          onComplete:
            - ls -la
            - save_tests test-results.xml

      - name: npm_build
        type: Bash
        configuration:
          affinityGroup: dbp_group
          inputSteps:
            - name: npm_test
        execution:
          onStart:
            - ls -la
            - npm run build
          onComplete:
            - ls -la
            - save_tests test-results.xml

      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: trialhisol202107.jfrog.io/docker-local/cicd-jfrog-cli-github-actions  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputSteps:
            - name: npm_build
          inputResources:
            - name: dbp_repo2
          integrations:
            - name: art                            # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: art                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image2

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info2

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: docker-dev
          integrations:
            - name: art
          inputResources:
            - name: dbp_build_info2
          outputResources:
            - name: dbp_promoted_build_info2
